name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Docker Auth
      run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        docker build -t asia-northeast1-docker.pkg.dev/neon101/neon101-repo/neon101-web-fe:latest .
        docker push asia-northeast1-docker.pkg.dev/neon101/neon101-repo/neon101-web-fe:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy neon101-web-fe \
          --image=asia-northeast1-docker.pkg.dev/neon101/neon101-repo/neon101-web-fe:latest \
          --region=asia-northeast1 \
          --platform=managed \
          --allow-unauthenticated
